# Generated by Django 5.1.5 on 2025-04-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ecom',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=255)),
                ('stock_code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(max_length=30)),
                ('invoice_date', models.DateTimeField()),
                ('unit_price', models.FloatField()),
                ('customer_id', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
