# Generated by Django 5.1.5 on 2025-04-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ecom',
            new_name='EcomCountry',
        ),
        migrations.AlterModelTable(
            name='ecomcountry',
            table='ecom-country',
        ),
    ]
