# Generated by Django 5.1.5 on 2025-04-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_rename_ecom_ecomcountry_alter_ecomcountry_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('invoice_count', models.IntegerField()),
                ('product_count', models.IntegerField()),
            ],
            options={
                'db_table': 'customer-summary',
            },
        ),
    ]
